name: Update kursBTC.txt from Google Sheets

on:
  schedule:
    - cron: '0 * * * *'  # Каждую минуту (или задайте свой график)
  workflow_dispatch:  # Запуск по кнопке в интерфейсе GitHub

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get data from Google Sheets
        id: fetch_data
        run: |
          DATA=$(curl -s "https://script.google.com/macros/s/AKfycbzZvQMpbmeQJMbU9lezLeSecNBXy4-ofHnrpWozXhmjfCGDZXm0z62Q3m-1vRnvzkSD/exec")
          echo "$DATA" > kursBTC.txt
          echo "Data fetched: $DATA"
      
      - name: Commit changes
        run: |
          git config --global user.name "your-username"
          git config --global user.email "your-email@example.com"
          git add kursBTC.txt
          git commit -m "Update kursBTC.txt"
          git push

      - name: Deploy to GitHub Pages
        run: |
          git checkout gh-pages
          git add kursBTC.txt
          git commit -m "Deploy updated kursBTC.txt"
          git push origin gh-pages
