name: Деплой 

on:
  push:
    branches:
      - main  # Запускается при push в ветку main (или другую, если нужно)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Выбираем Ubuntu как среду выполнения

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Создать папку build, если она не существует
      - name: Create build folder
        run: |
          mkdir -p build  # создаём папку build, если её нет

      # Шаг 3: Копировать все файлы в папку build (кроме самой папки build)
      - name: Copy files to build folder
        run: |
          shopt -s extglob  # включаем поддержку шаблонов для исключений
          cp -r !(build) ./build  # копируем все файлы, кроме папки build, в папку build

      # Шаг 4: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Ветка, на которой будет опубликован сайт
          folder: ./build  # Папка с файлам, которые нужно опубликовать
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Токен для аутентификации
