name: Update kursBTC.txt from Google Sheets

on:
  schedule:
    - cron: '*/30 * * * *'  # Запускать каждые 30 минут
  workflow_dispatch:  # Позволяет запуск вручную через GitHub

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Клонируем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3
    
      # 2️⃣ Получаем данные из Google Sheets
      - name: Get data from Google Sheets
        id: fetch_data
        run: |
          DATA=$(curl -s "https://script.google.com/macros/s/AKfycbzZvQMpbmeQJMbU9lezLeSecNBXy4-ofHnrpWozXhmjfCGDZXm0z62Q3m-1vRnvzkSD/exec")
          echo "Last updated: $(date)" > kursBTC.txt  # Добавляем дату
          echo "$DATA" >> kursBTC.txt  # Записываем данные
          echo "Data fetched: $DATA"
      
      # 3️⃣ Коммит изменений в репозиторий
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase
          git add kursBTC.txt
          
          # Проверяем, есть ли изменения
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit"
            exit 0
          fi
          
          git commit -m "Auto-update kursBTC.txt"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/hamsauno/Miner.git HEAD:main

      # 4️⃣ Разворачиваем на GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git checkout main
          git add kursBTC.txt
          
          # Проверяем, есть ли изменения перед коммитом
          if git diff --cached --quiet; then
            echo "No changes detected, skipping deployment"
            exit 0
          fi
          
          git commit -m "Deploy updated kursBTC.txt"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/hamsauno/Miner.git HEAD:main
