name: Update kursBTC.txt from Google Sheets

on:
  schedule:
    - cron: '*/30 * * * *'  # Запуск каждые 30 минут
  workflow_dispatch:

concurrency:
  group: "pages-deploy"
  cancel-in-progress: true

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get data from Google Sheets
        id: fetch_data
        run: |
          DATA=$(curl -s -L "https://script.google.com/macros/s/AKfycbzZvQMpbmeQJMbU9lezLeSecNBXy4-ofHnrpWozXhmjfCGDZXm0z62Q3m-1vRnvzkSD/exec")
          echo "$DATA" > kursBTC.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add kursBTC.txt
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit"
            exit 0
          fi

          git commit -m "Auto-update kursBTC.txt"
          git pull --rebase origin main || echo "No need to rebase"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/hamsauno/Miner.git HEAD:main || echo "Push failed"

      - name: Wait before deployment
        run: sleep 30  # Даем время предыдущему процессу завершиться

      - name: Deploy to GitHub Pages
        run: |
          git checkout main
          
          if git diff --quiet kursBTC.txt; then
            echo "No changes in kursBTC.txt, skipping deployment"
            exit 0
          fi
          
          git add kursBTC.txt
          git commit -m "Deploy updated kursBTC.txt"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/hamsauno/Miner.git HEAD:main

