name: Update kursBTC.txt from Google Sheets

on:
  schedule:
    - cron: '0 * * * *'  # Запуск каждый час
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Отключаем стандартную аутентификацию

      - name: Get data from Google Sheets
        id: fetch_data
        run: |
          DATA=$(curl -s "https://script.google.com/macros/s/AKfycbzZvQMpbmeQJMbU9lezLeSecNBXy4-ofHnrpWozXhmjfCGDZXm0z62Q3m-1vRnvzkSD/exec")
          echo "$DATA" > kursBTC.txt
          echo "Data fetched: $DATA"

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Используем токен из секретов
        run: |
          git config --global user.name "hamsauno"
          git config --global user.email "hamsauno74@gmail.com"
          git add kursBTC.txt
          git commit -m "Update kursBTC.txt" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/hamsauno/Miner.git HEAD:gh-pages
