name: Update kursBTC.txt from Google Sheets

on:
  schedule:
    - cron: '*/30 * * * *'  # Запуск каждые 30 минут
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Получаем данные из Google Sheets
      - name: Get data from Google Sheets
        id: fetch_data
        run: |
          # Получаем данные с вашего Google Apps Script URL
          DATA=$(curl -s "https://script.googleusercontent.com/macros/echo?user_content_key=AehSKLgLdax6ZNE_eHqIstmYtJnoAk1WrxZtAUmTcT4CgtGp284ocMelLeRCyhgufkroj-2k8vRRDg2R6uiqF2ou2dSp38shwC9Elx89hnKbqQH5yng4SnANNUlNyVnH2pExvOJB3FMSj_b1Mpq_KhXd78y-7QIEQqGRU73iOrzEDyF_OKNVHDiwDkpR1Yrjx1mvANaOLq9wx1HaZgXhgcRShGQ6fEb2CsCIiMtvEflCY20dBSuhgnkXkGenfGp8EROzLgED19pcsNNlR8N8G0n91deN4LGJFg&lib=MQtGzJNGnibUXnVLkhdE-7APAnCuUMyA7")
          echo "$DATA" > kursBTC.txt  # Записываем данные в файл kursBTC.txt

      # 3️⃣ Коммитим и пушим изменения, если они есть
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Проверяем, есть ли изменения
          git add kursBTC.txt
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit"
            exit 0
          fi

          git commit -m "Auto-update kursBTC.txt"
          git pull --rebase origin main || echo "No need to rebase"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/hamsauno/Miner.git HEAD:main || echo "Push failed"

      # 4️⃣ Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git checkout main
          git add kursBTC.txt
          
          # Проверяем, есть ли изменения перед коммитом
          if git diff --cached --quiet; then
            echo "No changes detected, skipping deployment"
            exit 0
          fi
          
          git commit -m "Deploy updated kursBTC.txt"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/hamsauno/Miner.git HEAD:main
