name: Update kursBTC.txt from Google Sheets

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Получение данных из Google Apps Script
      - name: Get data from Google Sheets
        id: fetch_data
        run: |
          # Получаем данные с вашего Google Apps Script URL
          DATA=$(curl -s "https://script.googleusercontent.com/macros/echo?user_content_key=AehSKLhtv72v-Cat2KWlGqeomi2gzjWouIeZA7V_z7BXMLTB1l8ZyCm9jhRkCGZoAKj9TU_qhtfT1m8y9U-AseGTnjSxUi0QypC_fPu68eEhw8CHw2r-cR5rEZfneUFZa--WuhVbQc7VxwRtr4Cg0PKQ0j2z2yWl0LBQb5pKM_M9VFjffJk-AiB3ED4NETqqOJFjZY841K6WBfg4JUQiR6gj4-Gbq9YmXtmMIL6b6U86SAgGKQcGRE15iQI9r7P38lEZ_PFC-cl9kCBDZOi12u3BPgvDjOCpTQ&lib=MQtGzJNGnibUXnVLkhdE-7APAnCuUMyA7")
          echo "$DATA" > kursBTC.txt  # Записываем данные в файл kursBTC.txt

      # Шаг 3: Коммит изменений в репозиторий
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Проверяем, есть ли изменения
          git add kursBTC.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Коммитим изменения
          git commit -m "Auto-update kursBTC.txt with new data"
          
          # Пушим изменения в репозиторий
          git push origin main
